const MOVEMENT_SCHEMA_ = 'nbp_attendance';
const MOVEMENT_TABLE_ = 'personnel_movements';
const MOVEMENT_HISTORY_SHEET_ = 'OFFICE_MOVEMENT';

function setupMovementTable() {
  let conn, stmt;
  try {
    conn = getNeonConnection_(); stmt = conn.createStatement();
    stmt.execute(['CREATE TABLE IF NOT EXISTS '+MOVEMENT_SCHEMA_+'.'+MOVEMENT_TABLE_+' (','movement_id text PRIMARY KEY,','employee_key text NOT NULL,','full_name_snapshot text NOT NULL,','from_camp text NOT NULL,','from_office text NOT NULL,','to_camp text NOT NULL,','to_office text NOT NULL,','position_snapshot text,','admin_order_no text NOT NULL,','admin_order_date date,','effective_date date NOT NULL,','remarks text,',"status text NOT NULL DEFAULT 'PENDING_RECEIPT',",'created_by text,','created_at timestamptz NOT NULL DEFAULT now(),','received_by text,','received_at timestamptz,',"CONSTRAINT personnel_movements_status_check CHECK (status IN ('PENDING_RECEIPT','COMPLETED','CANCELLED'))",');'].join(' '));
    try{stmt.execute('ALTER TABLE '+MOVEMENT_SCHEMA_+'.'+MOVEMENT_TABLE_+' ADD COLUMN IF NOT EXISTS position_snapshot text')}catch(ignore){}
    stmt.execute('CREATE INDEX IF NOT EXISTS idx_personnel_movements_status ON '+MOVEMENT_SCHEMA_+'.'+MOVEMENT_TABLE_+' (status, effective_date DESC)');
    stmt.execute('CREATE INDEX IF NOT EXISTS idx_personnel_movements_employee ON '+MOVEMENT_SCHEMA_+'.'+MOVEMENT_TABLE_+' (employee_key, created_at DESC)');
    return {ok:true,table:MOVEMENT_SCHEMA_+'.'+MOVEMENT_TABLE_};
  } finally {if(stmt)stmt.close();if(conn)conn.close()}
}
function getMovementBootstrap(){const r=getMovementReferenceData_();return {personnel:r.personnel,offices:r.offices,pending:listPendingMovements_()}}
function getPendingMovementCount(){let c,s,r;try{c=getNeonConnection_();s=c.prepareStatement('SELECT COUNT(*) FROM '+MOVEMENT_SCHEMA_+'.'+MOVEMENT_TABLE_+" WHERE status = 'PENDING_RECEIPT'");r=s.executeQuery();return r.next()?Number(r.getInt(1)||0):0}finally{if(r)r.close();if(s)s.close();if(c)c.close()}}
function getMovementReferenceData_(){
  const ss=getSpreadsheet_(),list=ss.getSheetByName('LIST'),directory=ss.getSheetByName('OFFICE_DIRECTORY');if(!list||!directory)throw new Error('Movement Center requires LIST and OFFICE_DIRECTORY sheets.');
  const v=list.getDataRange().getDisplayValues(),h=(v[0]||[]).map(x=>String(x).trim()),ix=n=>h.indexOf(n);['BADGE NUMBER','RANK','LAST NAME','FIRST NAME','MIDDLE NAME','SUFFIX','CAMP','OFFICE'].forEach(n=>{if(ix(n)<0)throw new Error('LIST is missing required column: '+n)});
  const personnel=v.slice(1).filter(row=>String(row[ix('BADGE NUMBER')]||'').trim()).map(row=>({recordId:ix('RECORD ID')>=0?String(row[ix('RECORD ID')]||'').trim():'',badgeNumber:String(row[ix('BADGE NUMBER')]||'').trim(),rank:String(row[ix('RANK')]||'').trim(),fullName:[row[ix('RANK')],row[ix('FIRST NAME')],row[ix('MIDDLE NAME')],row[ix('LAST NAME')],row[ix('SUFFIX')]].filter(Boolean).join(' ').replace(/\s+/g,' ').trim(),camp:String(row[ix('CAMP')]||'').trim(),office:String(row[ix('OFFICE')]||'').trim(),position:ix('POSITION / DESIGNATION')>=0?String(row[ix('POSITION / DESIGNATION')]||'').trim():''}));
  const ov=directory.getDataRange().getDisplayValues(),oh=(ov[0]||[]).map(x=>String(x).trim()),ci=oh.indexOf('CAMP'),oi=oh.indexOf('OFFICE'),ai=oh.indexOf('ACTIVE'),si=oh.indexOf('SORT ORDER');if(ci<0||oi<0)throw new Error('OFFICE_DIRECTORY requires CAMP and OFFICE columns.');
  const offices=ov.slice(1).filter(row=>{const c=String(row[ci]||'').trim(),o=String(row[oi]||'').trim(),a=ai<0?true:!['FALSE','NO','0','INACTIVE'].includes(String(row[ai]||'').trim().toUpperCase());return c&&o&&a}).map(row=>({camp:String(row[ci]||'').trim(),office:String(row[oi]||'').trim(),sortOrder:si>=0?Number(row[si]||0):0}));return {personnel,offices};
}
function createPersonnelMovement(payload){return createPersonnelMovementInternal_(payload,getMovementReferenceData_())}
function createPersonnelMovementInternal_(payload,refs){
  payload=payload||{};const key=String(payload.employeeKey||'').trim(),tc=String(payload.toCamp||'').trim(),to=String(payload.toOffice||'').trim(),pos=String(payload.position||'').trim(),ao=String(payload.adminOrderNo||'').trim(),aod=String(payload.adminOrderDate||'').trim(),ed=String(payload.effectiveDate||'').trim(),rem=String(payload.remarks||'').trim();if(!key||!tc||!to||!ao||!ed)throw new Error('Personnel, destination, Admin Order No., and effective date are required.');
  const p=refs.personnel.find(x=>String(x.badgeNumber)===key);if(!p)throw new Error('Personnel record was not found.');if(p.camp===tc&&p.office===to)throw new Error('Destination is the same as the current assignment.');if(!refs.offices.some(o=>o.camp===tc&&o.office===to))throw new Error('Destination office is not valid or active.');if(hasPendingMovement_(key))throw new Error('This personnel already has a pending movement awaiting receipt.');
  const id=Utilities.getUuid();let c,s;try{c=getNeonConnection_();s=c.prepareStatement(['INSERT INTO '+MOVEMENT_SCHEMA_+'.'+MOVEMENT_TABLE_,'(movement_id, employee_key, full_name_snapshot, from_camp, from_office, to_camp, to_office, position_snapshot, admin_order_no, admin_order_date, effective_date, remarks, status, created_by)',"VALUES (?, ?, ?, ?, ?, ?, ?, NULLIF(?, ''), ?, NULLIF(?, '')::date, ?::date, NULLIF(?, ''), 'PENDING_RECEIPT', ?)"].join(' '));[id,key,p.fullName,p.camp,p.office,tc,to,pos||p.position,ao,aod,ed,rem,getMovementUserEmail_()].forEach((v,i)=>s.setString(i+1,String(v==null?'':v)));s.executeUpdate()}finally{if(s)s.close();if(c)c.close()}return {ok:true,movementId:id,status:'PENDING_RECEIPT',person:p.fullName,from:p.camp+' / '+p.office,to:tc+' / '+to};
}
function createPersonnelMovementsBulk(payload){
  payload=payload||{};const keys=[...new Set((payload.employeeKeys||[]).map(x=>String(x).trim()).filter(Boolean))];if(!keys.length)throw new Error('Select at least one personnel.');if(keys.length>200)throw new Error('Bulk transfer is limited to 200 personnel at a time.');const refs=getMovementReferenceData_(),created=[],skipped=[];
  keys.forEach(key=>{try{created.push(createPersonnelMovementInternal_({employeeKey:key,toCamp:payload.toCamp,toOffice:payload.toOffice,adminOrderNo:payload.adminOrderNo,adminOrderDate:payload.adminOrderDate,effectiveDate:payload.effectiveDate,remarks:payload.remarks},refs))}catch(e){skipped.push({employeeKey:key,error:e.message||String(e)})}});return {ok:created.length>0,created:created.length,skipped:skipped,results:created};
}
function receivePersonnelMovement(id){
  id=String(id||'').trim();if(!id)throw new Error('Movement ID is required.');const m=getMovementById_(id);if(!m)throw new Error('Movement record was not found.');if(m.status==='COMPLETED')return {ok:true,alreadyCompleted:true,movement:m};if(m.status!=='PENDING_RECEIPT')throw new Error('Only pending movements can be received.');const cur=getPersonnelAssignmentFromSheet_(m.employeeKey);if(!cur)throw new Error('Personnel could not be found in LIST.');const dest=cur.camp===m.toCamp&&cur.office===m.toOffice,origin=cur.camp===m.fromCamp&&cur.office===m.fromOffice;if(!dest&&!origin)throw new Error('Assignment conflict: LIST currently shows '+cur.camp+' / '+cur.office+'.');if(origin)updatePersonnelAssignmentInSheet_(m.employeeKey,m.toCamp,m.toOffice,m.position);appendOfficeMovementHistory_(m,cur.recordId);completeMovement_(id,getMovementUserEmail_());return {ok:true,movementId:id,status:'COMPLETED',person:m.fullName,assignment:m.toCamp+' / '+m.toOffice};
}
function receivePersonnelMovementsBulk(ids){const unique=[...new Set((ids||[]).map(x=>String(x).trim()).filter(Boolean))];if(!unique.length)throw new Error('Select at least one pending movement.');if(unique.length>200)throw new Error('Bulk receipt is limited to 200 personnel at a time.');const done=[],failed=[];unique.forEach(id=>{try{done.push(receivePersonnelMovement(id))}catch(e){failed.push({movementId:id,error:e.message||String(e)})}});try{clearReferenceDataCache()}catch(ignore){}return {ok:done.length>0,received:done.length,failed:failed,results:done}}
function appendOfficeMovementHistory_(m,recordId){const sh=getSpreadsheet_().getSheetByName(MOVEMENT_HISTORY_SHEET_);if(!sh)throw new Error(MOVEMENT_HISTORY_SHEET_+' sheet was not found.');const admin='Admin Order: '+m.adminOrderNo+(m.adminOrderDate?' dated '+m.adminOrderDate:'');sh.appendRow([recordId||'',m.employeeKey,m.fromOffice,m.toOffice,m.position||'',m.effectiveDate,'',[admin,m.remarks].filter(Boolean).join(' | ')])}
function listPendingMovements(){return listPendingMovements_()}
function listPendingMovements_(){let c,s,r;const out=[];try{c=getNeonConnection_();s=c.prepareStatement(['SELECT movement_id, employee_key, full_name_snapshot, from_camp, from_office, to_camp, to_office,',"COALESCE(position_snapshot, ''), admin_order_no, COALESCE(admin_order_date::text, ''), effective_date::text, COALESCE(remarks, ''), status,","COALESCE(created_by, ''), created_at::text",'FROM '+MOVEMENT_SCHEMA_+'.'+MOVEMENT_TABLE_,"WHERE status = 'PENDING_RECEIPT'",'ORDER BY effective_date ASC, created_at ASC'].join(' '));r=s.executeQuery();while(r.next())out.push(movementRowToObject_(r));return out}finally{if(r)r.close();if(s)s.close();if(c)c.close()}}
function hasPendingMovement_(key){let c,s,r;try{c=getNeonConnection_();s=c.prepareStatement('SELECT 1 FROM '+MOVEMENT_SCHEMA_+'.'+MOVEMENT_TABLE_+" WHERE employee_key = ? AND status = 'PENDING_RECEIPT' LIMIT 1");s.setString(1,key);r=s.executeQuery();return r.next()}finally{if(r)r.close();if(s)s.close();if(c)c.close()}}
function getMovementById_(id){let c,s,r;try{c=getNeonConnection_();s=c.prepareStatement(['SELECT movement_id, employee_key, full_name_snapshot, from_camp, from_office, to_camp, to_office,',"COALESCE(position_snapshot, ''), admin_order_no, COALESCE(admin_order_date::text, ''), effective_date::text, COALESCE(remarks, ''), status,","COALESCE(created_by, ''), created_at::text",'FROM '+MOVEMENT_SCHEMA_+'.'+MOVEMENT_TABLE_,'WHERE movement_id = ?'].join(' '));s.setString(1,id);r=s.executeQuery();return r.next()?movementRowToObject_(r):null}finally{if(r)r.close();if(s)s.close();if(c)c.close()}}
function movementRowToObject_(r){return {movementId:String(r.getString(1)),employeeKey:String(r.getString(2)),fullName:String(r.getString(3)),fromCamp:String(r.getString(4)),fromOffice:String(r.getString(5)),toCamp:String(r.getString(6)),toOffice:String(r.getString(7)),position:String(r.getString(8)||''),adminOrderNo:String(r.getString(9)),adminOrderDate:String(r.getString(10)||''),effectiveDate:String(r.getString(11)),remarks:String(r.getString(12)||''),status:String(r.getString(13)),createdBy:String(r.getString(14)||''),createdAt:String(r.getString(15)||'')}}
function completeMovement_(id,user){let c,s;try{c=getNeonConnection_();s=c.prepareStatement('UPDATE '+MOVEMENT_SCHEMA_+'.'+MOVEMENT_TABLE_+" SET status='COMPLETED', received_by=?, received_at=now() WHERE movement_id=? AND status='PENDING_RECEIPT'");s.setString(1,String(user||''));s.setString(2,id);if(!s.executeUpdate())throw new Error('Movement could not be completed.')}finally{if(s)s.close();if(c)c.close()}}
function getPersonnelAssignmentFromSheet_(key){const sh=getSpreadsheet_().getSheetByName('LIST');if(!sh)throw new Error('LIST sheet was not found.');const v=sh.getDataRange().getDisplayValues(),h=(v[0]||[]).map(x=>String(x).trim()),bi=h.indexOf('BADGE NUMBER'),ci=h.indexOf('CAMP'),oi=h.indexOf('OFFICE'),ri=h.indexOf('RECORD ID'),pi=h.indexOf('POSITION / DESIGNATION');if(bi<0||ci<0||oi<0)throw new Error('LIST requires BADGE NUMBER, CAMP, and OFFICE columns.');for(let i=1;i<v.length;i++)if(String(v[i][bi]).trim()===key)return {row:i+1,recordId:ri>=0?String(v[i][ri]||'').trim():'',camp:String(v[i][ci]).trim(),office:String(v[i][oi]).trim(),position:pi>=0?String(v[i][pi]||'').trim():'',campCol:ci+1,officeCol:oi+1,positionCol:pi>=0?pi+1:0};return null}
function updatePersonnelAssignmentInSheet_(key,camp,office,position){const sh=getSpreadsheet_().getSheetByName('LIST'),cur=getPersonnelAssignmentFromSheet_(key);if(!cur)throw new Error('Personnel could not be found in LIST.');sh.getRange(cur.row,cur.campCol).setValue(camp);sh.getRange(cur.row,cur.officeCol).setValue(office);if(cur.positionCol&&position)sh.getRange(cur.row,cur.positionCol).setValue(position);SpreadsheetApp.flush()}
function getMovementUserEmail_(){try{return String(Session.getActiveUser().getEmail()||Session.getEffectiveUser().getEmail()||'').trim()}catch(ignore){return ''}}
